/* 권한관리 */
CREATE TABLE ACL_AUTH (
	AUTH_CD VARCHAR2(20) NOT NULL, /* 권한코드 */
	AUTH_NM VARCHAR2(50), /* 명칭 */
	AUTH_DC VARCHAR2(200), /* 설명 */
	REG_DT VARCHAR2(14), /* 등록일 */
	MODI_DT VARCHAR2(14) /* 수정일 */
);

COMMENT ON TABLE ACL_AUTH IS '권한관리';

COMMENT ON COLUMN ACL_AUTH.AUTH_CD IS '권한코드';

COMMENT ON COLUMN ACL_AUTH.AUTH_NM IS '명칭';

COMMENT ON COLUMN ACL_AUTH.AUTH_DC IS '설명';

COMMENT ON COLUMN ACL_AUTH.REG_DT IS '등록일';

COMMENT ON COLUMN ACL_AUTH.MODI_DT IS '수정일';

CREATE UNIQUE INDEX EZ_AUTH
	ON ACL_AUTH (
		AUTH_CD ASC
	);

ALTER TABLE ACL_AUTH
	ADD
		CONSTRAINT EZ_AUTH
		PRIMARY KEY (
			AUTH_CD
		);

/* 사용자권한관리 */
CREATE TABLE ACL_USER_AUTH (
	USER_ID VARCHAR2(20) NOT NULL, /* 사용자식별키 */
	AUTH_CD VARCHAR2(20), /* 권한코드 */
	REG_DT VARCHAR2(14), /* 등록일 */
	MODI_DT VARCHAR2(14) /* 수정일 */
);

COMMENT ON TABLE ACL_USER_AUTH IS '사용자권한관리';

COMMENT ON COLUMN ACL_USER_AUTH.USER_ID IS '사이트별 사용자키';

COMMENT ON COLUMN ACL_USER_AUTH.AUTH_CD IS '권한코드';

COMMENT ON COLUMN ACL_USER_AUTH.REG_DT IS '등록일';

COMMENT ON COLUMN ACL_USER_AUTH.MODI_DT IS '수정일';

CREATE UNIQUE INDEX EZ_USER_AUTH
	ON ACL_USER_AUTH (
		USER_ID ASC
	);

ALTER TABLE ACL_USER_AUTH
	ADD
		CONSTRAINT EZ_USER_AUTH
		PRIMARY KEY (
			USER_ID
		);

/* 권한별 리소스관리 */
CREATE TABLE ACL_AUTH_RESOURCE (
	AUTH_CD VARCHAR2(20) NOT NULL, /* 권한코드 */
	RESOURCE_CD VARCHAR2(50) NOT NULL, /* 리소스코드 */
	REG_DT VARCHAR2(14), /* 등록일 */
	MODI_DT VARCHAR2(14) /* 수정일 */
);

COMMENT ON TABLE ACL_AUTH_RESOURCE IS '권한별 리소스관리';

COMMENT ON COLUMN ACL_AUTH_RESOURCE.AUTH_CD IS '권한코드';

COMMENT ON COLUMN ACL_AUTH_RESOURCE.RESOURCE_CD IS '리소스코드';

COMMENT ON COLUMN ACL_AUTH_RESOURCE.REG_DT IS '등록일';

COMMENT ON COLUMN ACL_AUTH_RESOURCE.MODI_DT IS '수정일';

CREATE UNIQUE INDEX PK_ACL_AUTH_RESOURCE
	ON ACL_AUTH_RESOURCE (
		AUTH_CD ASC,
		RESOURCE_CD ASC
	);

ALTER TABLE ACL_AUTH_RESOURCE
	ADD
		CONSTRAINT PK_ACL_AUTH_RESOURCE
		PRIMARY KEY (
			AUTH_CD,
			RESOURCE_CD
		);

/* 리소스관리 */
CREATE TABLE ACL_RESOURCE (
	RESOURCE_CD VARCHAR2(50) NOT NULL, /* 리소스코드 */
	RESOURCE_NM VARCHAR2(100), /* 명칭 */
	RESOURCE_DC VARCHAR2(200), /* 설명 */
	RESOURCE_URL VARCHAR2(300), /* 패턴 */
	REG_DT VARCHAR2(20), /* 등록일 */
	MODI_DT VARCHAR2(20) /* 수정일 */
);

COMMENT ON TABLE ACL_RESOURCE IS '리소스관리';

COMMENT ON COLUMN ACL_RESOURCE.RESOURCE_CD IS '리소스코드';

COMMENT ON COLUMN ACL_RESOURCE.RESOURCE_NM IS '명칭';

COMMENT ON COLUMN ACL_RESOURCE.RESOURCE_DC IS '설명';

COMMENT ON COLUMN ACL_RESOURCE.RESOURCE_URL IS '패턴';

COMMENT ON COLUMN ACL_RESOURCE.REG_DT IS '등록일';

COMMENT ON COLUMN ACL_RESOURCE.MODI_DT IS '수정일';

CREATE UNIQUE INDEX PK_EZ_ROLE
	ON ACL_RESOURCE (
		RESOURCE_CD ASC
	);

ALTER TABLE ACL_RESOURCE
	ADD
		CONSTRAINT PK_EZ_ROLE
		PRIMARY KEY (
			RESOURCE_CD
		);

ALTER TABLE ACL_USER_AUTH
	ADD
		CONSTRAINT FK_ACL_AUTH_TO_ACL_USER_AUTH
		FOREIGN KEY (
			AUTH_CD
		)
		REFERENCES ACL_AUTH (
			AUTH_CD
		);

ALTER TABLE ACL_USER_AUTH
	ADD
		CONSTRAINT FK_EZ_USER_TO_ACL_USER_AUTH
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES EZ_USER (
			USER_ID
		);

ALTER TABLE ACL_AUTH_RESOURCE
	ADD
		CONSTRAINT FK_ACL_AUTH_TO_ACL_AUTH_RESOURCE
		FOREIGN KEY (
			AUTH_CD
		)
		REFERENCES ACL_AUTH (
			AUTH_CD
		);

ALTER TABLE ACL_AUTH_RESOURCE
	ADD
		CONSTRAINT FK_ACL_RESOURCE_TO_ACL_AUTH_RESOURCE
		FOREIGN KEY (
			RESOURCE_CD
		)
		REFERENCES ACL_RESOURCE (
			RESOURCE_CD
		);



CREATE TABLE ACL_AUTH_HIERARCHY
(
	SEQ              NUMBER NOT NULL,
	PARENT_AUTH_CD   VARCHAR2 (20) NOT NULL,
	CHILD_AUTH_CD    VARCHAR2 (20) NOT NULL
) ;

CREATE UNIQUE INDEX ACL_AUTH_HIERARCHY_PK
ON ACL_AUTH_HIERARCHY
(
	SEQ ASC
);

CREATE UNIQUE INDEX ACL_AUTH_HIERARCHY_UK
ON ACL_AUTH_HIERARCHY
(
	PARENT_AUTH_CD ASC,
	CHILD_AUTH_CD ASC
);

ALTER TABLE ACL_AUTH_HIERARCHY ADD(
	CONSTRAINT ACL_AUTH_HIERARCHY_PK PRIMARY KEY (SEQ));

ALTER TABLE ACL_AUTH_HIERARCHY ADD(
	CONSTRAINT ACL_AUTH_HIERARCHY_UK UNIQUE (PARENT_AUTH_CD, CHILD_AUTH_CD));

CREATE TABLE EZ_USER
(
	USER_ID   VARCHAR2 (20) NOT NULL,
	USER_NM   VARCHAR2 (20) NOT NULL,
    USER_PWD  VARCHAR2 (100) NOT NULL
) ;

COMMENT ON TABLE EZ_USER IS '사용자' ;

COMMENT ON COLUMN EZ_USER.USER_ID IS '유저ID' ;

COMMENT ON COLUMN EZ_USER.USER_NM IS '사용자명' ;
COMMENT ON COLUMN EZ_USER.USER_PWD IS '비밀번호' ;

CREATE UNIQUE INDEX EZ_USER_PK
ON EZ_USER
(
	USER_ID ASC
);

ALTER TABLE EZ_USER ADD(
	CONSTRAINT EZ_USER_PK PRIMARY KEY (USER_ID));

INSERT INTO EZ_USER VALUES('admin', '관리자', 'admin');
INSERT INTO EZ_USER VALUES('user', '사용자', 'user');

commit;